name: 'kyverno-action'
description: 'Tests resources against kyverno policies'
author: 'Christian Kotzbauer'
inputs:
  token:
    required: true
    description: 'Github token'
    default: ${{ github.token }}
  kyverno-version:
    required: false
    description: 'Kyverno version'
    default: v1.4.2
  resource-files:
    required: false
    description: 'YAML files to test'
    default: ""
  chart-dir:
    required: false
    description: 'Directory of Helm-Chart to test'
    default: ""
  value-files:
    required: false
    description: 'Value-Files for Helm-Chart to test'
    default: ""
  rule-files:
    required: true
    description: 'Kyverno-Rule-Files'
runs:
  using: 'node12'
  main: 'dist/index.js'
